# Generated by Django 3.0.3 on 2020-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('totalRevenue', models.FloatField()),
                ('priorRevenue', models.FloatField()),
                ('costOfGoodsSold', models.FloatField()),
                ('operatingExpenses', models.FloatField()),
                ('cashBalance', models.FloatField()),
                ('currentAssets', models.FloatField()),
                ('currentLiabilities', models.FloatField()),
                ('longTermLiabilities', models.FloatField()),
                ('ownerSatisfaction', models.IntegerField()),
                ('employeeSatisfaction', models.IntegerField()),
                ('newCustomers', models.IntegerField()),
                ('startCustomers', models.IntegerField()),
                ('endCustomers', models.IntegerField()),
                ('rewardsProgram', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('totalInventory', models.FloatField()),
                ('deadInventory', models.FloatField()),
                ('expansion', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
            ],
        ),
    ]
